### PR TITLE
Squashed version of pull request #2

### PR DESCRIPTION
**Pull request by viktorradnai**
This is the same as #2 but with a bunch of incremental changes (fixes, etc) squashed.

### CODE REVIEW

**Comment by viktorradnai** [comment]
Please verify that you are happy with this, I got into merge hell while rebasing the start of the history as I was rebasing onto the current master.

**Comment by viktorradnai** [comment]
Please ignore the previous comment, I have now realised the error of my ways and will rebase again onto a more sensible starting point. D'oh.

**Comment by dragonsmith** [comment]
That is great and way more readable right now! Thank you!
One last thing. Please, select branch `development` so that I can add missing Test Kitchen configuration and run it to check new systemd integration before merging to master.

I cannot merge into master right away because some of our use cases are configured to use master branch without any version limitations(I know it is not the right way, but it is like that).

**Comment by viktorradnai** [comment]
Hey, it took me four tries but I think I've got it squashed properly :) I've changed the base to the development branch as requested.

I have unfortunately undone many of the Chef 13 compatibility fixes while merging (the addition of the new_resource prefix everywhere). This needs to be added back at some point. I'm still using tools geared for Chef 12, if you have a newer ChefDK then feel free to put this back.

**Comment by viktorradnai** [comment]
How did you test Chef 13 compatibility? I could not find flags for this in Cookstyle and couldn't get Foodcritic to warn about the lack of 'new_resource' prefixes in the custom resources.

**Comment by MattMencel** [comment]
I'm working on it this morning.  I want to add support for the wmi exporter now....but I'm having trouble merging your changes into my fork.  I may just fork your fork and try it that way.  I will test the Chef 13 compatibility as well.

Unless you have a better suggestion.

**Comment by viktorradnai** [comment]
@MattMencel If you send a pull request to the "squashed" branch of my fork and I merge that, I think it will show up in this PR :) A bit hacky but I haven't got a better idea. I had a bit of trouble consolidating your changes with the ones made by @dragonsmith and then squashing the commit history to make it more readable so this will probably result in the least amount of parallel lines in the Git history.

**Comment by MattMencel** [comment]
This is an example of the deprecation warnings in Chef 13 that I addressed in my PR to your PR.  Looks like they plan to remove that in Chef 14.

```
rename web_listen_address to new_resource.web_listen_address at 1 location:
    - /var/chef/cache/cookbooks/prometheus_exporters/resources/node.rb:90:in `block in class_from_file'
   See https://docs.chef.io/deprecations_namespace_collisions.html for further details.
```

**Comment by viktorradnai** [comment]
@dragonsmith I think this is ready to be merged now as Chef 13/14 compatibility has been restored by @MattMencel.

**Comment by dragonsmith** [comment]
@viktorradnai Thank you very much! Merging now!

**Comment by dragonsmith** [comment]
I think it may take me up to Friday to test all changes for my corner cases and merge into the master branch. I'll open an issue and mention you both to start new discussion if I'll bump into an unclear situation.

Thanks again!

**Pull request merged**
