### PR TITLE
Use the external service management cookbook.

### PR DESCRIPTION
**Pull request by f9n**
- [poise-service](https://github.com/poise/poise-service)

### CODE REVIEW

**Comment by dragonsmith** [comment]
@f9n Hello!

My original idea was to keep this cookbook free of any dependencies. That makes this cookbook much easier to be integrated. Service management is not that complex, especially when Chef has its own `systemd_unit` resource.

I cannot guaranty I will merge this PR, but let me think for a bit and sleepover with your suggestion in mind.

Thank you!

**Comment by f9n** [comment]
@dragonsmith Hello,

Yes, you are right. It's good that the cookbook doesn't depend on any dependencies. Maybe we can create a library for creating service management files on this cookbook. But my vote is on external cookbook :) We can create a new cookbook or support an [external cookbook](https://github.com/poise/poise-service).

**Comment by dragonsmith** [comment]
@f9n
I've checked `poise-service` cookbook repo and it seems like an almost unsupported one.

Here is my issue regarding that: https://github.com/poise/poise-service/issues/50

Let's wait for a week and see what response we will get. Using an unsupported cookbook looks not very promising.

**Comment by dragonsmith** [comment]
@f9n well, we've got an answer.

I suggest we make a small helper library out of our code for this cookbook. Do you have a spare time to make it? I think I can do this by the end of the next week myself.

**Pull request closed without merging**
