### PR TITLE
Enhanced Sys V Init support and tests

### PR DESCRIPTION
**Pull request by viktorradnai**
Hi, there are a lot of changes in here, I have also included everything from WIU/chef-prometheus-exporters and tweaked it further, as @MattMencel's PR has never been merged. 

The tests require a .kitchen.yml which I did not commit as I was using our EC2 setup. Vagrant should work for anyone but I didn't try it yet. Also I only tested this on Redhat 6 so the systemd stuff will need to be verified.

### CODE REVIEW

**Comment by dragonsmith** [comment]
@viktorradnai Wow, thank you for such a big pull request! I need to review thoroughly. But from the first glance, I think it needs to be squashed a least partly. I'll try to give you any thoughts in 3-4 hours.

**Comment by dragonsmith** [comment]
@viktorradnai, @MattMencel, @petracvv,
 
Thank you all for a significant work you did. I'm sorry again for I was inattentive all this time. That is a terrible behavior for an opensource project author.

I've looked through all commits & changes and here are few points I think we need to do:

1) As I thought initially, a lot of commits need be squashed. Please, may I ask you to do so, @viktorradnai ?
2) Let's recreate this pull request. This time to a branch `development`. I'm not ready to merge it straight to master and want to try it in our beta environment first.

I also think we should finish with Test Kitchen configuration and create `kitchen.yml` for local testing before merging to master and add Chef 13 support as it was proposed in 71328fe7b61d4d74c4e2bb6866099fed0507e801. I can do that right after we merge the PR.

Thank you again for your help!!!

**Comment by viktorradnai** [comment]
HI @dragonsmith, thanks for looking at this. I will squash any commits with identical messages and anything obvious (eg. typo fixes following a feature add). Have you got an idea on approximately how many commits you'd like to see?  If posible, I'd like to avoid going through all the changes in order to group them by the type of change that was done.

**Comment by MattMencel** [comment]
@viktorradnai do you need me to squash mine too or are you just going to do them all in your PR?

**Comment by viktorradnai** [comment]
Hi @MattMencel, I'm squashing yours as well. I'm proposing to squash and reorder the commits in my master branch as below -- then I'll probably have to open a new pull request instead of this one:

pick e89f469 Basic CentOS support. Some Cookstyle cleanup. Fix upstart template so Chef 12.5+ doesn't throw warnings.
p 17ad661 snmp_exporter
f 4b0e7ac url variable
f 288b340 no path
pick 47e37f3 node_exporter service for CentOS < 7
f c030428 node_exporter service for CentOS < 7
f 2fc89fb fix chmod
f a9ed373 fix return code
f ad3685a fix return code
f 3ce4255 fix return code
pick c35cce9 systemd unit blocks
pick f2ba68b Add install action to node recipe
pick c6a817e Convert to upstream resource to avoid systemd cookbook dependency
f 84a4378 Need a create action
pick 71328fe Initial Chef13 support
f 6615539 Last Chef13 deprecation notices
f 3dc7a7e Do not verify service files as it fails inexplicably
pick c739088 Make sure to extract exporter before creating the service
pick 59aca3d Sysv init support for the SNMP collector and various fixes
f 271e61e Use systemd cookbook from public Supermarket
f d278de8 Add .gitignore
f 912a288 Improvements to init scripts
f 01384f8 Bugfixes for postgres_exporter
f 8eef1b6 Really set redis process to start as the specified user
pick c1900e3 Removed dependency on systemd cookbook
pick 56daada Added tests
f f469492 Cookstyle fix
f 9af6d89 Improvements for tests
pick 43dfb6e Updated changelog
pick 4f486af Added checksum for SNMP exporter
pick 8d4ff04 Split log directories to fix logfile permission issue when exporters aren't running as root
pick 246c186 Documentation update and version bump
f abe827c Updated changelog

@dragonsmith @MattMencel are you happy with this plan?

**Comment by dragonsmith** [comment]
@viktorradnai , the plan looks good. Thank you!

**Comment by viktorradnai** [comment]
This PR has been superseded by PR #3

**Pull request closed without merging**
